name: mini_social_network
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.1
  flutter_dotenv: ^5.1.0
  file_picker: ^10.3.3
  image_picker: ^1.2.0
  flutter_riverpod: ^2.5.1
  path_provider: ^2.1.5
  flutter_sound: ^9.28.0
  permission_handler: ^12.0.1
  flutter_secure_storage: ^9.2.4
  socket_io_client: ^3.1.2
  dio: ^5.9.0
  video_player: ^2.10.0
  audioplayers: ^6.5.1
  flutter_local_notifications: ^19.5.0
  intl: ^0.20.2
  flutter_colorpicker: ^1.1.0
  screenshot: ^3.0.0
  photo_view: ^0.15.0
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  device_info_plus: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/icon.png"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
